nohup etcd \
  --data-dir=/home/remote/milvus_local_testing/data/etcd \
  --listen-client-urls=http://127.0.0.1:2379 \
  --advertise-client-urls=http://127.0.0.1:2379 > etcd.log 2>&1 &


localStorage:
  path: /home/remote/milvus_local_testing/milvus_cache


nohup ./minio server /home/remote/milvus_local_testing/data/minio_data_folder --address :9000 --console-address :9001 > minio.log 2>&1 &
